//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Mongo2DocumentDB.Models
{
    public partial class WordOccurrence
    {
        public int Id { get; set; }
        public int MailId { get; set; }
        public int WordId { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual Mail Mail { get; set; }
        public virtual Word Word { get; set; }
    }
}
