//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mongo2SQL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnronSqlContext : DbContext
    {
        public EnronSqlContext(string connectionStringName)
            : base(connectionStringName)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<EmailAccount> EmailAccount { get; set; }
        public virtual DbSet<Header> Header { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }
        public virtual DbSet<Recipient> Recipient { get; set; }
        public virtual DbSet<Sender> Sender { get; set; }
        public virtual DbSet<Word> Word { get; set; }
        public virtual DbSet<WordOccurrence> WordOccurrence { get; set; }
    }
}
